# FIXED
dsp_bios_cfg_c.obj: dsp_bios_cfg_c.c
dsp_bios_cfg_c.obj: dsp_bios_cfg.h
dsp_bios_cfg_c.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/std.h
dsp_bios_cfg_c.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/tistdtypes.h
dsp_bios_cfg_c.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/hst.h
dsp_bios_cfg_c.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/pip.h
dsp_bios_cfg_c.obj: C:/EEE/CCStudio4.1/ccsv4/tools/compiler/c6000/include/stddef.h
dsp_bios_cfg_c.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/fxn.h
dsp_bios_cfg_c.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/sts.h
dsp_bios_cfg_c.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/swi.h
dsp_bios_cfg_c.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/hwi.h
dsp_bios_cfg_c.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/tsk.h
dsp_bios_cfg_c.obj: C:/EEE/CCStudio4.1/ccsv4/tools/compiler/c6000/include/stdarg.h
dsp_bios_cfg_c.obj: C:/EEE/CCStudio4.1/ccsv4/tools/compiler/c6000/include/stddef.h
dsp_bios_cfg_c.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/knl.h
dsp_bios_cfg_c.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/atm.h
dsp_bios_cfg_c.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/que.h
dsp_bios_cfg_c.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/mem.h
dsp_bios_cfg_c.obj: C:/EEE/CCStudio4.1/ccsv4/tools/compiler/c6000/include/stddef.h
dsp_bios_cfg_c.obj: C:/EEE/CCStudio4.1/ccsv4/tools/compiler/c6000/include/stdarg.h
dsp_bios_cfg_c.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/prd.h
dsp_bios_cfg_c.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/sem.h
dsp_bios_cfg_c.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/obj.h
dsp_bios_cfg_c.obj: C:/EEE/CCStudio4.1/ccsv4/tools/compiler/c6000/include/stddef.h
dsp_bios_cfg_c.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/sys.h
dsp_bios_cfg_c.obj: C:/EEE/CCStudio4.1/ccsv4/tools/compiler/c6000/include/stdarg.h
dsp_bios_cfg_c.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/trg.h
dsp_bios_cfg_c.obj: C:/EEE/CCStudio4.1/ccsv4/tools/compiler/c6000/include/stddef.h
dsp_bios_cfg_c.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/_hook.h
dsp_bios_cfg_c.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/log.h
dsp_bios_cfg_c.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/_log.h
dsp_bios_cfg_c.obj: C:/EEE/CCStudio4.1/bios_5_41_02_14/packages/ti/bios/include/trc.h
